# Generated by Django 4.1 on 2022-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created',
            new_name='joined_at',
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
