# Generated by Django 4.1 on 2022-09-03 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 4, 1, 1, 30, 603694), null=True),
        ),
    ]
